# Generated by Django 4.1.4 on 2022-12-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_remove_playlist_song_playlist_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
